### ISSUE TITLE
`require': cannot load such file -- expo-server-sdk (LoadError)

### ISSUE THREAD

**Issue by Nobilitate** [SleeplessByte/expo-server-sdk-ruby#2]
Hello,

Thanks for improving on the exponent-server-sdk and creating this package.

I'm new to Ruby and I've been running into an issue when attempting to require the gem.

#### Environment

macOS Monterey 12.14

```
$ ruby --version
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-darwin21]

$ gem --version
3.3.20

$ bundle --version
Bundler version 2.3.20
```

#### Setup & Issue

I followed the instructions in the README and created:

**Gemfile**
```
source "https://rubygems.org"

gem 'expo-server-sdk'
```

**app.rb**
```
require 'expo-server-sdk'

# Create a new Expo SDK client optionally providing an access token if you
# have enabled push security
client = Expo::Push::Client.new(accessToken: '<access-token>');

# Create the messages that you want to send to clients
messages = [];

# ... 
```

Upon running:
```
$ ruby app.rb
```

 I receive the following error:

```
~/.rbenv/versions/2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85
:in `require': cannot load such file -- expo-server-sdk (LoadError)
```

---

I noticed that, compared to other gems (`exponent-server-sdk`, for example) this gem doesn't have a file matching the gem name at `lib/`.

Instead it opts to construct it via a path: `lib/expo/server/sdk`.

I found that if I just modify the gem locally and create:

**lib/expo-server-sdk.rb**
```
# frozen_string_literal: true

require_relative 'expo/server/sdk/version'
require_relative 'push/client'

module Expo
  module Server
    module SDK # rubocop:disable Style/Documentation
      def self.push
        Expo::Push::Client
      end
    end
  end
end

```

Requiring the gem works without issue.

#### Question

As I said, I'm new to Ruby, so I'm not sure if there's a different way to require this gem so that it will load as-is?

**Comment by SleeplessByte** [comment]
Hi there! I understand your question. You're absolutely right that the instructions are currently incorrect. The reason I didn't notice before is that I am relying on `zeitwerk` to do the requiring for me, which is by default used in frameworks such as Rails.

However, the require path was _meant_ to be 

```ruby
require 'expo/server/sdk'
```

Which can be seen in the following example. I will update the README right away.

```ruby
# [start bundler]
require 'bundler/inline'

gemfile(true) do 
  source 'https://rubygems.org'
  gem 'expo-server-sdk'
end
# [end bundler]

# Everything above is similar to creating a Gemfile and then running bundle
# install, but this lets you do it inline!

require 'expo/server/sdk'

# Create a new Expo SDK client optionally providing an access token if you
# have enabled push security
client = Expo::Push::Client.new(access_token: '<access-token>');

puts client
```

**Comment by Nobilitate** [comment]
Great, I had a feeling I was missing something! Thanks for being attentive to this repo, it's very appreciated!
