### ISSUE TITLE
gem http failing with ArgumentError

### ISSUE THREAD

**Issue by alexandreh92** [SleeplessByte/expo-server-sdk-ruby#3]
Hi, thanks for your gem, I really apreciate your job here.

I'm trying to use this gem but `http` gem is failing in `lib/push/client.rb:259`:

Here's the trace:

```bash
Traceback (most recent call last):
	12: from /Users/alexandre/.rvm/gems/ruby-2.7.4/gems/expo-server-sdk-0.1.4/lib/push/client.rb:188:in `block (2 levels) in send'
	11: from /Users/alexandre/.rvm/gems/ruby-2.7.4/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `with'
	10: from /Users/alexandre/.rvm/gems/ruby-2.7.4/gems/connection_pool-2.2.5/lib/connection_pool.rb:59:in `handle_interrupt'
	 9: from /Users/alexandre/.rvm/gems/ruby-2.7.4/gems/connection_pool-2.2.5/lib/connection_pool.rb:60:in `block in with'
	 8: from /Users/alexandre/.rvm/gems/ruby-2.7.4/gems/connection_pool-2.2.5/lib/connection_pool.rb:78:in `checkout'
	 7: from /Users/alexandre/.rvm/gems/ruby-2.7.4/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:68:in `pop'
	 6: from /Users/alexandre/.rvm/gems/ruby-2.7.4/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:68:in `synchronize'
	 5: from /Users/alexandre/.rvm/gems/ruby-2.7.4/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:69:in `block in pop'
	 4: from /Users/alexandre/.rvm/gems/ruby-2.7.4/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:69:in `loop'
	 3: from /Users/alexandre/.rvm/gems/ruby-2.7.4/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:73:in `block (2 levels) in pop'
	 2: from /Users/alexandre/.rvm/gems/ruby-2.7.4/gems/connection_pool-2.2.5/lib/connection_pool/timed_stack.rb:169:in `try_create'
	 1: from /Users/alexandre/.rvm/gems/ruby-2.7.4/gems/expo-server-sdk-0.1.4/lib/push/client.rb:259:in `block in connect'
/Users/alexandre/.rvm/gems/ruby-2.7.4/gems/http-5.1.0/lib/http/chainable.rb:182:in `headers': wrong number of arguments (given 2, expected 1) (ArgumentError)
ArgumentError: wrong number of arguments (given 2, expected 1)
from /Users/alexandre/.rvm/gems/ruby-2.7.4/gems/http-5.1.0/lib/http/chainable.rb:182:in `headers'
```

Code:
```ruby
def send_message!(token)
  client = Expo::Push::Client.new(access_token: token)

  push_message = client.notification
                        .to(token)
                        .sound('default')
                        .body(body)

  client.send!([push_message])
end
```

**EDIT:** Got it working by changing:

```suggestion
- client = Expo::Push::Client.new(access_token: token)
+ client = Expo::Push::Client.new
```

**Comment by SleeplessByte** [comment]
Great. I'll check the case _with_ providing an `access token`.

**Comment by pvign** [comment]
Hi @SleeplessByte, 
I faced the same issue than @alexandreh92.
After digging a little bit it appears that the flaw is here: `http.headers('Authorization', "Bearer #{access_token}")`
([L259](https://github.com/SleeplessByte/expo-server-sdk-ruby/blob/3d28349b12f598dd25c5b0e45a332b95b533bf55/lib/push/client.rb#L259C77-L259C89))
According to the `http` wiki [here](https://github.com/httprb/http/wiki/Headers), `http.headers` accepts an hash while 2 arguments are passed here.
I replaced this line with:
`http.headers('Authorization' => "Bearer #{access_token}") if access_token` and it seems to work as expected.
It could also be replaced by `http.auth("Bearer #{access_token}") if access_token` according to this [page](https://github.com/httprb/http/wiki/Authorization-Header).
I am a newbie in Rails then I might missed something but otherwise I'll be happy to do a Pull Request if you think it is the right way.
Cheers

**Comment by SleeplessByte** [comment]
> Hi @SleeplessByte, 
> I faced the same issue than @alexandreh92.
> After digging a little bit it appears that the flaw is here: `http.headers('Authorization', "Bearer #{access_token}")`
> ([L259](https://github.com/SleeplessByte/expo-server-sdk-ruby/blob/3d28349b12f598dd25c5b0e45a332b95b533bf55/lib/push/client.rb#L259C77-L259C89))
> According to the `http` wiki [here](https://github.com/httprb/http/wiki/Headers), `http.headers` accepts an hash while 2 arguments are passed here.
> I replaced this line with:
> `http.headers('Authorization' => "Bearer #{access_token}") if access_token` and it seems to work as expected.
> It could also be replaced by `http.auth("Bearer #{access_token}") if access_token` according to this [page](https://github.com/httprb/http/wiki/Authorization-Header).
> I am a newbie in Rails then I might missed something but otherwise I'll be happy to do a Pull Request if you think it is the right way.
> Cheers
> 

Would love a PR!

**Comment by pvign** [comment]
> > Hi @SleeplessByte,
> > I faced the same issue than @alexandreh92.
> > After digging a little bit it appears that the flaw is here: `http.headers('Authorization', "Bearer #{access_token}")`
> > ([L259](https://github.com/SleeplessByte/expo-server-sdk-ruby/blob/3d28349b12f598dd25c5b0e45a332b95b533bf55/lib/push/client.rb#L259C77-L259C89))
> > According to the `http` wiki [here](https://github.com/httprb/http/wiki/Headers), `http.headers` accepts an hash while 2 arguments are passed here.
> > I replaced this line with:
> > `http.headers('Authorization' => "Bearer #{access_token}") if access_token` and it seems to work as expected.
> > It could also be replaced by `http.auth("Bearer #{access_token}") if access_token` according to this [page](https://github.com/httprb/http/wiki/Authorization-Header).
> > I am a newbie in Rails then I might missed something but otherwise I'll be happy to do a Pull Request if you think it is the right way.
> > Cheers
> 
> Would love a PR!

I've just submitted https://github.com/SleeplessByte/expo-server-sdk-ruby/pull/6

Thanks for your fast answer and your work on this gem 🙏

**Comment by SleeplessByte** [comment]
I'll review tomorrow. If you don't have a response by Sunday, please feel free to ping me!
